### ISSUE TITLE
One-way junctions do not respect block setting

### ISSUE THREAD

**Issue by Erikvv** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#124]
screenshot:
https://drive.google.com/open?id=1C3UdOr3H0htaS3ePTNHwnn5ORqIieLyS

The cars stop in the middle of the intersection and block cars from the other side.

If you attach a 2-way street to the intersection they don't any more.

I guess this is built-in behavior of Skylines?

**Comment by adiac** [comment]
It seems all cars coming from the bottom want to go to the most inner lane of the round about. So they are just blocking other directions. So no bug, rather a traffic flow problem.

Because of highway rules the cars are allowed to drive in the intersection, even if there is no space behind. If you connect another piece of road the highway rules seem not to apply anymore, so then no cars are allowed in an intersection by default (this can be changed with junction-restrictions).

Did you use the lane connector on these junctions? Try to assign your lanes better and make sure any turn is reachable for the cars (they can only change one lane at the very end of a segment and on junctions they can only change lanes if you allowed them to.) 

I hope this is helpful. If you have any other question on how to improve your traffic flow here just ask.

**Comment by Erikvv** [comment]
This is not specific to highways I tested with the 6-lane roads to be sure.

**Comment by Erikvv** [comment]
Tested with the 2-lane 1-way streets and they still stop in the middle of the intersection:

https://drive.google.com/open?id=1RWN8peSxpznla5JRqDX4FkD1ieVFjbiJ

**Comment by adiac** [comment]
I did some testing as well: 

As long as there is only one incoming or only one outgoing road highway rules apply and cars will drive into an intersection

https://picload.org/image/doolloal/snip_20180518171335.png
https://picload.org/image/doolloai/snip_20180518171353.png
