### ISSUE TITLE
On traffic lights, what units are the min/max times in?

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#154]
Game ticks? Milliseconds? Seconds? Days?

Wiki doesn't seem to define the units, nor does the UI.

**Comment by VictorPhilipp** [comment]
1 unit equals 64 game ticks.

**Comment by aubergine10** [comment]
I suspect most end-users will think more in terms of real-life seconds.

Would it be possible to estimate the number of seconds for the entered value and display it alongside the setting?

Or, better, have user input number of seconds and the mod works out, for current speed setting and fps, etc., how many game ticks that equates to (ie. silently converts from RL seconds to game ticks in the background at the instant the user updates the value).

**Comment by VictorPhilipp** [comment]
Time values should not depend on simulation speed. This would force players to continually increase the times to account for degradation in simulation speed that occurs due to city growth. Ticks are the in-game time resolution, not frames/seconds. For example, a vehicle with a certain velocity travels the same distance given a fixed number of ticks. Simulation speed not only depend on ticks but on the player's system performance and city progress.
