### ISSUE TITLE
Crossing restrictions do not apply to bicycles

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#174]
CommieKiller:
"Right now, cycles can still enter a crossing that has been disabled for pedestrians, which subsequently disrupt the traffic flow."

**Comment by aubergine10** [comment]
I've been setting up lots of pedestrian crossings recently and I've not noticed this issue (at least not since #142 was fixed). Cyclists seem to be respecting the junction restrictions, at least for me, across a fairly diverse range of road assets (vanilla, NeXT2, UK Roads, etc).

Note: I've only been playing in Left Hand Drive config, maybe it's RHD-specific?

**Comment by aubergine10** [comment]
Tested this a bit and still unable to reproduce. Situations tested:

* One way roads with ped tunnels - cyclists used ped tunnels
* Two way roads - cyclists went long way round to find alternate crossing
* Roads with bike lanes - cyclists respected crossing restrictions
* Corner and transition nodes - cyclists still found alternate routes

Suggest getting savegame from commiekiller to see exactly what's causing the reported behaviour.

**Comment by aubergine10** [comment]
Been a few weeks now and not seen any evidence of cyclists ignoring crossing restrictions, traffic lights or anything else.

**Comment by VictorPhilipp** [comment]
Thanks for your investigation. I came to the same conclusion. Closing this for now.
