### ISSUE TITLE
v1.10.10 causes industry to stop working due to lack of raw materials

### ISSUE THREAD

**Issue by charlie2alpha** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#194]
As the tittle of this issue says, with the latest version all my generic industry is getting abandoned due to lack of raw materials. And I'm talking about industrial areas that have multiple cargo hubs right next to them, so importing and exporting goods should have never been an issue.

**Comment by aubergine10** [comment]
Also seeing this. I have some warehouses literally right next to freight terminal (visually they are part of the terminal). They are stating 'not enough resources. There are plenty of cul-de-sacs in the area to enable vehicles to find short routes to destinations.

Note: I also use RealTime mod which was causing a glitch in number of virtual cims in industrial areas until recently. Not sure if that could be exacerbating the issue or not?

**Comment by Videonauth** [comment]
I only see some factories telling me of no materials when my highway gets blocked by something and the traffic is clogging up, but beside that I not seen that in large quantities happening, and as well not for long. I'm not using Real Time tho.

**Comment by charlie2alpha** [comment]
Since it was mentioned, let me state that I am **not** using the RealTime mod. There's also a relative discussion on the stream workshop page, others have encountered the same issue.

**Comment by aubergine10** [comment]
The issue has cleared up for me and everything seems to be working as normal (at least during daytime, might be different at night - I'm using RealTime mod).

**Comment by charlie2alpha** [comment]
For me it just gets worse over time. If use the patched version from #189 then everything goes back to normal in a short time. It's definitely something messed up in the 1.10.10 version.

**Comment by VictorPhilipp** [comment]
@charlie2alpha Could you please upload your savegame here?

**Comment by charlie2alpha** [comment]
OK, here it is, beware I have quite a few assets and mods.
[AutoSave.zip](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/files/2200036/AutoSave.zip)

**Comment by Blacksharesvk** [comment]
Hi, with new version of TM:PE I experience same, I didnt notice it because I had no abandoment mode on.
I had all the time high demand for industry and commercial + commercial showed NOT OPERATING NORMALLY (low and high both).

When I turned off TM:PE all shops showed OPERATING NORMALLY. 
No TM:PE  -  demand was at zero
With TM:PE - High demand no matter how many shops I builded. I had more shops than houses xD ratio 10:1
Commercial is 100% bugged with TMPE.

Another test try: I started just small city 500pop and 5shops.  Tried to turn off TMPE to see what happens. 
Same result.

**Comment by VictorPhilipp** [comment]
@charlie2alpha Thanks for your savegame! I don't think I would have been able to figure out what the problem is without it.

I believe the issue occurs due when combining cul-de-sacs and multi-lane roads in industrial areas, like on the screenshot below. Heavy vehicles (juggernauts) are currently unable to perform u-turns at dead ends (this is a bug!). Since they are the only type of vehicles able to load raw materials your industry buildinds are not supplied.
![grafik](https://user-images.githubusercontent.com/4333935/42850613-c9e63c30-8a28-11e8-86df-7ad50a719205.png)

While investigating your issue I also discovered that this cemetery
![grafik](https://user-images.githubusercontent.com/4333935/42850852-f393c510-8a29-11e8-8be5-5b3056178354.png)
cannot be empties. Guess what, it's due to the dead end.

Expect me to fix this within the next few days.

**Comment by aubergine10** [comment]
Interesting, I was just about to make a bug report that a water pumping station (or whatever it's called - those things that send out water vacuum trucks) was not having it's bins emptied. It was at end of 2-lane cul-de-sac. Interestingly, however, the incineration plant was just down the road from it, on the same side of the road (also the side that my vehicles drive on). I moved the water plant further away from end of road and bins started to be collected. It seems to be proximity of building to end of cul-de-sac road that causes problem.
