### ISSUE TITLE
Odd pathfinding quirk - Will take much longer route instead of simple lane change

### ISSUE THREAD

**Issue by Drift91** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#198]
![cities 2018-07-17 21-01-21-826](https://user-images.githubusercontent.com/2638764/42854124-48ce1d40-8a08-11e8-81ad-610897f8563b.jpg)
In the above screenshot I noticed a truck was taking the yellow route instead of the red route, which would make more sense. Upon closer inspection I noticed absolutely no traffic was taking the red route at all, despite there being a cargo hub at the source, outside the screenshot. At the marked intersection I used the lane connector to allow any of the two lanes to connect to any of the other two output lanes and suddenly all the traffic came flowing through the red route.

Now it's my understanding that vehicles are supposed to be able to change lanes at intersections like that without me having to set up the lane connector. Am I right that this is unexpected behaviour, or is it just a quirk in the unusual configuration of that intersection I've set up?

[Here's my save if you need it.](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/files/2203991/Kyle.1-15.zip)

**Comment by VictorPhilipp** [comment]
Your issue is caused by these forward arrows:
![grafik](https://user-images.githubusercontent.com/4333935/42968834-bf3be0f0-8ba4-11e8-90cb-a9cd2989c952.png)

Due to the angle between the road segments you need to use right pointing lane arrows.
I used the lane connector tool to identify which direction the lane arrows must point to:
![grafik](https://user-images.githubusercontent.com/4333935/42968872-d8c963da-8ba4-11e8-8809-e9943ff266c1.png)

Traffic starts flowing again (I removed the lane connections since they are not necessary):
![grafik](https://user-images.githubusercontent.com/4333935/42969132-7a2e661c-8ba5-11e8-8d5a-3769dab5a558.png)
