### ISSUE TITLE
Cims wait in middle of road for a taxi that will collide with them

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#208]
I've always noticed this trait, even in vanilla, that cims wait for their taxis in the middle of the road.

If you first-person cam a taxi, it's like playing [Carmageddon](https://www.wikiwand.com/en/Carmageddon) with the taxi hunting down zombie cims to run over.

These cims slow down other traffic, in much the same way pedestrians crossing a road at a crossing slow down traffic.

I perceive two possible solutions:

1. Add blades to the hub caps of vehicles + cim splatter effects = fully Carmageddon-ify C:SL, or...
2. Make cims wait for their taxis on the pavement (or just anywhere else other than standing in the road)

**Comment by Videonauth** [comment]
After deleting at least one million of those merry turn around breakers, I'm opting for blades at the hubcaps :D

**Comment by VictorPhilipp** [comment]
I have also seen that happening multiple times. You should ask the author of the asset to fix the problem. However, I will investigate on what the underlying problem.

**Comment by VictorPhilipp** [comment]
moved

**Comment by williamrwright** [comment]
> moved

Curious to know where this issue was moved to.  I am having this problem.

**Comment by krzychu124** [comment]
> > moved
> 
> Curious to know where this issue was moved to. I am having this problem.

![image](https://user-images.githubusercontent.com/19638970/127863252-23a72935-c853-436a-b35d-5f6ea81e143c.png)

**Comment by originalfoo** [comment]
Possible way to fix this issue is to use [Building Spawn Points](https://steamcommunity.com/sharedfiles/filedetails/?id=2511258910) mod to check location of the **Taxi** spawn/despawn point for nearby buildings to see if any have it in the middle of road - then simply move the spawn point so it's no longer on the road. The cim seems to wait at or near the spawn point. I've no idea if there's some way to automate that city wide.
