### ISSUE TITLE
Different timed traffic light programs, configurable per daytime interval

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#26]
http://steamcommunity.com/workshop/filedetails/discussion/583429740/357286033299200961/

**Comment by VictorPhilipp** [comment]
At specific intervals, priority signs may take over controlling the junction. The traffic light then flashes yellow. (@GordonDry)

**Comment by Deliverer7** [comment]
Not sure if this should go here, but here goes:
Provide the ability to mark one state of a timed light plan as the "default" or "rest" state. I'll give an example to demonstrate the use of this feature.

There is an intersection of an arterial road and a collector road. There needs to be a traffic light (instead of priority signs) because there is a heavy volume on the arterial road. The volume coming from the collector road is very light. We have a timing plan such that the maximum amount of time cars would have to queue on the collector road is 45 seconds (aka the max timer of arterial road). The arterial road is in a green state, the max timer has started counting down from 45, but there are no cars in the queue on the collector road. The states will cycle at the end of 45 seconds, even though there are no calls for service on any conflicting movement (wait = 0). The arterial road will cycle to red until all the other states are cycled through. If we could set the state that serves the arterial road as the "default" or "rest" state, then if the wait value is equal to 0, it would not cycle to the next state.

Ideas:
1. If the active state is "default/rest", and wait value = 0, then do not start max timer. When wait value > 0 (a car has queued for service on a conflicting movement), begin the max timer. The max timer runs out due to heavy volume, and the state terminates as normal, moving to the next state in the timing plan.

2. If the current state is NOT the "default/rest" state, and flow = 0 and wait = 0, immediately terminate the current state and jump to the "default/rest" state (regardless of current position in timing plan).


Assumptions:
1. Players would (optionally) indicate which state is the "default/rest" state in their timing plan (state with heaviest anticipated volume/flow).
2. If player does not designate the "default/rest" state, the timing plan will operate as it currently does.

**Comment by VictorPhilipp** [comment]
Another related request: https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/113

**Comment by VictorPhilipp** [comment]
moved
