### ISSUE TITLE
Only cars on the most inner lane may u-turn

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#34]
@t1a2l

**Comment by DaEgi01** [comment]
👍

**Comment by williamrwright** [comment]
I've been having a lot of fun as a user of this mod, it's a welcome diversion whilst working on my dissertation.  I have so much respect for you & the contributors, this has really taken the game to another level.

Anyway, this revision piqued my interest.  For sake of discussion I'm assuming by /most inner lane/ you mean the lanes closest to the center. Thing is, sometimes big trucks turn around in the inner lane, and because there is so little space there, and they look ridiculous in the game.  A player might want to *disallow*, say, trucks in the inner lane from making a u-turn, and prefer them to u-turn from the outer lane.

In real life I've seen large trucks with trailers making u-turns from the outer lane.

Also this mod's powerful lane restrictions features allows one to, say, have a dedicated lane for busses and emergency vehicles.

In that case it's helpful to retain the ability for *all* lanes to u-turn if it's absolutely necessary to do so.

So all that to say, I'm curious whether if you make this change are you thinking of, say, creating default lane assignments that prevent the undesired u-turns or will it be something that totally prevents certain u-turns?

**Comment by VictorPhilipp** [comment]
I have implemented the feautre in version 1.8.4. However, I have not yet integrated your suggestion. I think this is solveable by allowing custom lane connections to override the default (strict) u-turning policy: Manually connecting lanes such that u-turns are intended to take place from a lane that are not the innermost lane (yes, it's the lane that lies in the center of the road) should be taken into account.

**Comment by williamrwright** [comment]
I think it's good, it seems as though it's a well conceived feature that will improve the flow of traffic and make things more realistic.

**Comment by williamrwright** [comment]
I think it's good, it seems as though it's a well conceived feature that will improve the flow of traffic and make things more realistic.
