### ISSUE TITLE
Regular cars on "Zonable Pedestrian Paved Tiny Road"

### ISSUE THREAD

**Issue by DaEgi01** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#55]
I use TM:PE together with Network Extensions 2.
My issue is that I still see regular cars on the "Zonable Pedestrian Paved Tiny Road".
My expectation was, that TM:PE would respect that roads.
I also tried vehicle restrictions and banned everything and also cleared all traffic afterwards.
Still cars drive on that roads.
I tried vehicle restrictions on other roads as well, yet without any effect.,
Could it be that they don't work anymore?

**Comment by VictorPhilipp** [comment]
Vehicle restrictions should work on every kind of road. I tested them on the pedestrian roads and they work for me. However, vehicle restrictions are ignored if there is no alternative route that can be taken by vehicles in order to circumvent restricted roads.

In version 1.10 I am going introduce a "vehicle restrictions aggression" factor.

![screenshot 62](https://user-images.githubusercontent.com/4333935/28293977-62166b52-6b57-11e7-8896-b79378fa78e9.png)

You then will be able to define how vehicle restrictions are handled by the path-finding algorithm. Selecting "Low"/"Medium"/"High" will then alter the path-finding costs associated with having vehicle restrictions and selecting "Strict" will prevent vehicles from entering restricted roads completely.

**Comment by DaEgi01** [comment]
Well, I made a big pedestrian only shopping area in my city and expected to see only supply and emergency vehicles there.
Since all other could theoretically walk there, I expected cims to park somewhere out of that area and walk the rest. Where is the error in my mental model?

**Comment by VictorPhilipp** [comment]
I am not sure what's the problem with your pedestrian zone. I can have a look at your savegame if you like.

Version 1.10 is now live. You can now try if setting the vehicle restrictions setting to _Strict_ helps in your case.

**Comment by DaEgi01** [comment]
I tried the option "strict" and it definitely helps. reduced traffic by a lot.
I still see some cars "looking for another parking spot" and other stuff ... have to look into it further.
